config/routes.rb
Rails.application.routes.draw do
  root to: 'homes#top'
  devise_for :users
  get "home/about" => "homes#about", as: "about"
  resources :users, only: [:index, :show, :edit, :update]
  resources :books, only: [:index, :show, :destroy, :create, :edit, :update]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  has_one_attached :image
  validates :title, presence: true
  validates :body, presence: true, length: { maximum: 200 }

  def get_image(width = 100, height = 100)
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      image.attach(
        io: File.open(file_path),
        filename: 'default-image.jpg',
        content_type: 'image/jpeg'
      )
    end
    image.variant(resize_to_limit: [width, height]).processed
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  attr_writer :login

  def login
    @login || self.name
  end

  has_many :books, dependent: :destroy
  has_one_attached :profile_image

  # バリデーション
  validates :name,
            presence: true,
            uniqueness: true,
            length: { minimum: 2, maximum: 20 }
  validates :introduction,
            length: { maximum: 50 }

  # プロフィール画像取得用メソッド
  def get_profile_image(width, height)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'no_image.jpg', content_type: 'image/jpeg')
    end
    profile_image.variant(resize_to_limit: [width, height]).processed
  end

  def self.find_for_database_authentication(warden_conditions)
    conditions = warden_conditions.dup
    if (name = conditions.delete(:login))
      where(conditions.to_h).where(["name = :value", { value: name }]).first
    else
      where(conditions.to_h).first
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!, except: [:top]
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :email])
    devise_parameter_sanitizer.permit(:sign_in, keys: [:name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name, :email, :introduction, :profile_image])
  end

  def after_sign_in_path_for(resource)
    user_path(resource)
  end

  def after_sign_out_path_for(resource)
    root_path
  end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :authenticate_user!, except: [:top, :about]
  #before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy] # ログイン必須
  before_action :set_book, only: [:show, :edit, :update, :destroy]                  # @bookの共通化
  before_action :correct_user, only: [:edit, :update, :destroy]                     # 権限チェック

  def new
    @book = Book.new
  end
  
  # 投稿データの保存
  def create
    #@book = Book.new(book_params)
    #@book.user_id = current_user.id
    @book = current_user.books.build(book_params) # current_userに紐付け
    #@book = current_user.books.new(book_params)
    if @book.save
      flash[:notice] = "You have created book successfully."
      redirect_to book_path(@book)
      #redirect_to @book
    else
      @books = Book.all
      @user = current_user
      render :index
    end
  end

  def index  
    @books = Book.all
    #@book = Book.new
    @book = current_user.books.build if user_signed_in?
    @user = current_user
  end

  def show
  @book = Book.find(params[:id])
  @user = @book.user
  end

  def edit 
    #@book = Book.find(params[:id]) 
    #if @user != current_user
    #  redirect_to books_path
    #end
  end

  def destroy
    #book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path
  end

  def update
  #@book = Book.find(params[:id])

  if @book.update(book_params)
    flash[:notice] = "You have updated book successfully."
    redirect_to book_path(@book)
  else
    render :edit
  end
end
  
  # 投稿データのストロングパラメータ
  private

  def set_book
    @book = Book.find(params[:id])
  end

  def correct_user
    unless current_user == @book.user
      flash[:alert] = "You are not authorized to edit this book."
      redirect_to books_path
    end
  end

  def book_params
    params.require(:book).permit(:title, :body)
  end
  
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:top, :about]
  def top
  end

  def about
  end
end

app/controllers/post_comments_controller.rb
class PostCommentsController < ApplicationController
  def create
    book = Book.find(params[:book_id])
    comment = current_user.post_comments.new(post_comment_params)
    comment.book_id = book.id
    comment.save
    redirect_to book_path(post_image)
  end

  private

  def post_comment_params
    params.require(:post_comment).permit(:comment)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, except: [:top, :about]
  before_action :set_user, only: [:show, :edit, :update]    # @user の取得を共通化
  before_action :correct_user, only: [:edit, :update]       # 権限チェック
  
  # 新規登録処理
  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to root_path, notice: "User created successfully."
    else
      render :new  # 失敗時にエラーを表示しつつフォームに戻る
    end
  end

  def index
    @users = User.all
    @book = current_user.books.build if user_signed_in? # サイドバー用フォーム 
    @display_user = current_user
  end

  def show
    @user = User.find(params[:id])
    @books = @user.books
    @book = current_user.books.build if user_signed_in? # サイドバー用フォーム
  end

  def edit
    #@user = User.find(params[:id])
    #if @user != current_user
    #  redirect_to books_path
    #end
  end

  def update
    #@user = User.find(params[:id])             # ユーザーの取得
    if @user.update(user_params)                  # ユーザーのアップデート
    redirect_to user_path(@user), notice: "You have updated user successfully."# ユーザーの詳細ページへのリダイレクト
    else
      render :edit
    end               
  end


  private

  def set_user
    @user = User.find(params[:id])
  end

  def correct_user
    unless current_user == @user
      flash[:alert] = "You are not authorized to edit this user."
      redirect_to user_path(current_user)
    #redirect_to books_path, alert: "You are not authorized to access this page." unless current_user == @user
    end
  end
  
  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/post_comments_helper.rb
module PostCommentsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/edit.html.erb
<div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
  <h1>Editing Book</h1>

  <% if @book && @book.errors.any? %>
    <div id="error_explanation">
      <%= pluralize(@book.errors.count, "error") %> prohibited this book from being saved:
      <ul>
        <% @book.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%= form_with model: @book, local: true do |f| %>
    <div class="form-group">
      <%= f.label :title %>
      <%= f.text_field :title, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= f.label :body, "Opinion" %>
      <%= f.text_area :body, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= f.submit "Update Book", class: "btn btn-success" %>
    </div>
  <% end %>

  <div class="mt-3">
    <%= link_to "Show", book_path(@book), class: "text-decoration-none me-3" %> |
    <%= link_to "Back", books_path, class: "text-decoration-none" %>
  </div>
</div>

app/views/books/index.html.erb
<div class="container">
  <div class="row">

    <%= render 'shared/sidebar', book: @book || Book.new, display_user: @user %>

    <div class="col-md-8 offset-md-1">
      <h2>Books</h2>
      <table class="table table-hover">
        <thead>
          <tr>
            <th></th>
            <th>Title</th>
            <th>Opinion</th>
          </tr>
        </thead>
        
        <tbody>
          <% @books.each do |book| %>
            <tr class="align-middle">
              <td>
                <% if book.user.present? %>
                  <p>
                    <%= link_to user_path(book.user) do %>
                      <%= image_tag book.user.get_profile_image(80,80) %>
                    <% end %>
                  </p>
                <% end %>
              </td>
              <td>
                <%= link_to book.title, book_path(book), class: "text-decoration-none" %>
              </td>
              <td>
                <p><%= book.body %></p>
              </td>
            </tr>
          </tbody>
        <% end %>
      </table>
    </div>
  </div>
</div>

app/views/books/new.html.erb
<div class="col-md-3">
  <h2>User info</h2>
  <% if current_user.present? %>
    <p><%= image_tag current_user.get_profile_image(100,100) %></p>
  <% end %>

  <table class="table">
    <thead>
      <tr>
        <th>name</th>
        <th>demouser</th>
      </tr>
      <tr>
        <th>introduction</th>
      <tr>
    </thead>
  </table>

  <div class="row">
    <%= link_to edit_users_path(current_user), class: "btn btn-block btn-outline-secondary" do %>
      <i class="fas fa-user-cog"></i>
    <% end %>
  </div>

  <h2>New book</h2>

  <% if @book && @book.errors.any? %>
    <div id="error_explanation">
      <%= pluralize(@book.errors.count, "error") %> prohibited this book from being saved:
      <ul>
        <% @book.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%= form_with model: @book, local: true do |f| %>
    <div class="form-group">
      <h4>Title</h4>
      <%= f.text_field :title, class: "form-control" %>
    </div>

    <div class="form-group">
      <h4>Opinion</h4>
      <%= f.text_area :body, class: "form-control" %>
    </div>

    <%= f.submit "Create Book", class: "btn btn-success mt-2" %>
  <% end %>
</div>

app/views/books/show.html.erb
<div class="container">
  <div class="row">

    <%= render 'shared/sidebar', book: @book || Book.new, display_user:@user %>

    <div class="col-md-8 offset-md-1">
      <h2>Book detail</h2>
      <table class="table table-hover table-inverse">

          <tbody>
            <tr class="align-middle">
              <td>
                <% if current_user.present? %>
                  <p>
                    <%= link_to user_path(@book.user) do %>
                      <%= image_tag @book.user.get_profile_image(80,80) %>
                    <% end %>
                  </p>
                  <p>
                      <%= link_to @book.user.name, user_path(@book.user), class: "text-decoration-none" %>
                  </p>
                  
                <% end %>
              </td>
              <td>
                <%= link_to @book.title, book_path(@book), class: "text-decoration-none" %>
              </td>
              <td>
                <p><%= @book.body %></p>
              </td>
              <td>
                <% if @book.user == current_user %>
                  <%= link_to "Edit", edit_book_path(@book), class: "btn btn-sm btn-success mb-1" %><br>
                <% end %>
              </td>
              <td>
                <% if @book.user == current_user %>
                  <%= link_to "Destroy", book_path(@book), method: :delete, data: { confirm: "本当に消しますか？" }, class: "btn btn-sm btn-danger" %>
                <% end %>  
              </td>
            </tr>
          </tbody>
      </table>
    </div>
  </div>
</div>

app/views/homes/about.html.erb
<!-- app/views/homes/about.html.erb -->
<div class="d-flex justify-content-center">
  <div class="text-left">
    <h1>Welcome to <i class="fa-solid fa-book"></i><b>Bookers</b>!</h1>
    <p>This is a web application that you can share your opinions about books.</p>
  </div>
</div>

app/views/homes/top.html.erb
<div class="container mt-3">
  <div class="row justify-content-center">
    <div class="mx-auto col-11 col-sm-10 col-lg-8 col-xl-6">

      <h1 class="ps-5">welcome to <i class="fa-solid fa-book"></i><b>Bookers!!</b></h1>

      <div class="ps-5">
        <p><b>In <i class="fa-solid fa-book"></i>Bookers</b></p>
        <p>you can share and exchange your opinions, impressions, and emotions</p>
        <p>about various books!</p>
      </div>

      <div class="d-flex flex-column align-items-center mt-3">
        <%= link_to "Log in", new_user_session_path, class: "btn btn-primary w-75 mb-2" %>
        <%= link_to "Sign up", new_user_registration_path, class: "btn btn-success w-75" %>
      </div>

    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <script src="https://kit.fontawesome.com/640d7a3cf3.js" crossorigin="anonymous"></script>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>

  <body>
    <header class="shadow-sm">
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
          <a class="navbar-brand" href="/"><span>Bookers</span></a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown"
                        aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">

            <% if user_signed_in? %>
            <li class="nav-item">
              <%= link_to user_path(current_user), class: "nav-link text-light" do %>
              <i class="fa-solid fa-home"></i> Home
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to users_path, class: 'nav-link text-light' do %>
              <i class="fa-solid fa-users"></i>Users
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to books_path, class: 'nav-link text-light' do %>
              <i class="fa-solid fa-book-open"></i>Books
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to destroy_user_session_path, method: :delete, class: 'nav-link text-light' do %>
              <i class="fa-solid fa-right-from-bracket"></i>Log out
              <% end %>
            </li>
            <% else %>
            <li class="nav-item">
              <%= link_to root_path, class: "nav-link text-light" do %>
              <i class="fa-solid fa-home"></i> Home
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to about_path, class: "nav-link text-light" do %>
              <i class="fa-solid fa-link"></i> About
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to new_user_registration_path, class: 'nav-link text-light' do %>
              <i class="fa-solid fa-user-plus"></i> Sign up
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to new_user_session_path, class: 'nav-link text-light' do %>
              <i class="fa-solid fa-sign-in-alt"></i> Log in
              <% end %>
            </li>
            <% end %>
            </ul>
          </div>
        </div>
      </nav>
      <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    </header>

    <main>
      <div class="container">
        <div class="mt-4">
        </div>
      </div>

      <% if defined?(@book) && @book.errors.any? %>
        <div class="container mt-3">
          <div class="row">
            <div class="col-md-8 col-lg-7">
              <div id="error_explanation">
                <h3>
                  <%= pluralize(@book.errors.count, "error") %> prohibited this obj from being saved:
                </h3>

                <ul class="ps-3">
                  <% @book.errors.full_messages.each do |msg| %>
                    <li><%= msg %></li>
                  <% end %>
                </ul>
              </div>
            </div>
          </div>
        </div>
      <% end %>
 
      <% flash.each do |message_type, message| %>
        <div class="flash-message <%= message_type %>"><%= message %></div>
      <% end %>

    <%= yield %>
    </main>

    <footer>
      <div class="d-flex justify-content-center align-items-center mt-5" style="height: 40px;">
        <p>CopyRight Infratop.inc</p>
      </div>
    </footer>

  </body>
</html>

app/views/post_images/new.html.erb
<div class="col-md-3">
  <h2>User info</h2>
  <% if current_user.present? %>
    <p><%= image_tag current_user.get_profile_image(100,100) %></p>
  <% end %>

  <table class="table">
    <thead>
      <tr>
        <th>name</th>
        <th>demouser</th>
      </tr>
      <tr>
        <th>introduction</th>
      <tr>
    </thead>
  </table>

  <div class="row">
    <%= link_to edit_user_path(current_user), class: "btn btn-block btn-outline-secondary" do %>
      <i class="fas fa-user-cog">
      </i>
    <% end %>
  </div>


  <h2>New book</h2>
  <%= form_with model: @post_image do |f| %>
    <h4>Title</h4>
    <%= f.text_field :shop_name %>
    <h4>Opinion</h4>
    <%= f.text_area :caption %>
    <%= f.submit 'Create Book', class: "btn btn-success" %>
  <% end %>

</div>

app/views/shared/_sidebar.html.erb
<div class="col-md-3">
  <% if current_user.present? %>


      <h2>User info</h2>
      <%= image_tag display_user.get_profile_image(100,100), class: "sidebar-profile-img" %>

        <table class="table">
          <tbody>
            <tr>
              <th>name</th>
              <td><%= display_user.name %></td>
            </tr>
            <tr>
              <th>introduction</th>
            <td><%= display_user.introduction %></td>
            </tr>
          </tbody>
        </table>


          <div class="row mb-4">
            <div class="col">
              <%= link_to edit_user_path(display_user), class: "btn btn-block btn-outline-secondary" do %>
                <i class="fas fa-user-cog"></i>
              <% end %>
            </div>
          </div>

          <h2>New book</h2>
          <% book_for_form = Book.new %>
          <%= form_with model: book_for_form, local: true do |f| %>
            <div class="form-group">
              <h4>Title</h4>
              <%= f.text_field :title, class: "form-control" %>
            </div>

            <div class="form-group">
              <h4>Opinion</h4>
              <%= f.text_area :body, class: "form-control" %>
            </div>

            <%= f.submit 'Create Book', class: "btn btn-success" %>

      <% end %>
  <% end %>
</div>

app/views/users/edit.html.erb
<div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
  <h1>User info</h1>

  <% filtered_errors = @user.errors.full_messages.reject { |msg| msg == "Name can't be blank" } %>
<% if filtered_errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(filtered_errors.count, "error") %> prohibited this obj from being saved:</h2>
    <ul>
      <% filtered_errors.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

  <%= form_with model: @user, url: user_path(@user), local: true do |f| %>
    <div class="form-group">
      <label for="inputName">Name</label>
      <%= f.text_field :name, class: "form-control name" %>
    </div>

    <div class="form-group">
      <label for="inputImage">Image</label>
      <%= f.file_field :profile_image, placeholder: "プロフィール画像", accept: "image/*" %>
    </div>

    <div class="form-group">
      <label for="user_introduction">Introduction</label>
      <%= f.text_area :introduction, class: "form-control introduction" %>
    </div>

    <div class="form-group">
      <%= f.submit "Update User", class: "btn btn-secondary" %>
    </div>
  <% end %>

  <div class="mt-3">
    <%= link_to "Show", user_path(@user), class: "text-decoration-none me-3" %> |
    <%= link_to "Back", users_path, class: "text-decoration-none" %>
  </div>
</div>

app/views/users/index.html.erb
<div class="container">
  <div class="row">

    <%= render 'shared/sidebar', book: @book || Book.new, display_user: @display_user %>

    <div class="col-md-8 offset-md-1">
      <h2>Users</h2>
      <table class="table table">
        <thead>
          <tr>
            <th>image</th>
            <th>name</th>
          </tr>
        </thead>
        
        <tbody>
          <% @users.each do |user| %>
            <tr class="align-middle">
              <td>
                <%= link_to user_path(user) do %>
                  <%= image_tag user.get_profile_image(80,80), class: "user-list-img" %>
                <% end %>
              </td>
              <td>
                <%= link_to user_path(user), class: "text-decoration-none" do %>
                  <p><strong><%= user.name %></strong></p>
                <% end %>
              </td>
              <td>
                <%= link_to "Show", user_path(user), class: "text-decoration-none" %>
              </td>
            </tr>
           <% end %> 
          </tbody>
        
      </table>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="container">
  <div class="row align-items-stretch">
  
    <%= render 'shared/sidebar', book: @book || Book.new, display_user: @user %>

    <div class="col-md-8 offset-md-1">
      <h2>Books</h2>
      <table class="table table-hover table-inverse">

        <thead>
          <tr>
            <th></th>
            <th>Title</th>
            <th>Opinion</th>
          </tr>
        </thead>
        
        <tbody>
          <% @books.each do |book| %>
            <tr class="align-middle">
              <td>
                <%= link_to user_path(book.user) do %>
                  <%= image_tag book.user.get_profile_image(80,80) %>
                <% end %>
              </td>
              <td>
                <%= link_to book.title, book_path(book), class: "text-decoration-none" %>
              </td>
              <td>
                <p><%= book.body %></p>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>